services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sevenwonders
      POSTGRES_USER: sevenwonders
      POSTGRES_PASSWORD: sevenwonders
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  db_test:
    image: postgres:15
    environment:
      POSTGRES_DB: seven_wonders_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  db_data: {}