// Entité Card pour la logique métier Seven Wonders
export enum CardType {
  CIVIL = 'Bâtiment Civil',
  SCIENCE = 'Bâtiment Scientifique',
  MILITARY = 'Bâtiment Militaire',
  RAW_MATERIAL = 'Matière Première',
  MANUFACTURED_GOOD = 'Produit Manufacturé',
  COMMERCIAL = 'Bâtiment Commercial',
  GUILD = 'Guilde',
}

export class Card {
  constructor(
    public readonly name: string,
    public readonly type: CardType,
    public readonly minPlayers: number,
    public readonly age: 1 | 2 | 3,
  ) {}
}

// Liste complète des cartes de 7 Wonders (édition de 2020)
export const ALL_CARDS: Card[] = [
  // Matières Premières
  new Card('Chantier', CardType.RAW_MATERIAL, 3, 1),
  new Card('Chantier', CardType.RAW_MATERIAL, 4, 1),
  new Card('Cavité', CardType.RAW_MATERIAL, 3, 1),
  new Card('Cavité', CardType.RAW_MATERIAL, 5, 1),
  new Card('Bassin Argileux', CardType.RAW_MATERIAL, 3, 1),
  new Card('Bassin Argileux', CardType.RAW_MATERIAL, 5, 1),
  new Card('Filon', CardType.RAW_MATERIAL, 3, 1),
  new Card('Filon', CardType.RAW_MATERIAL, 4, 1),
  
  new Card('Friche', CardType.RAW_MATERIAL, 6, 1),
  new Card('Excavation', CardType.RAW_MATERIAL, 4, 1),
  new Card('Fosse Argileuse', CardType.RAW_MATERIAL, 3, 1),
  new Card('Exploitation Forestière', CardType.RAW_MATERIAL, 3, 1),
  new Card('Gisement', CardType.RAW_MATERIAL, 5, 1),
  new Card('Mine', CardType.RAW_MATERIAL, 6, 1),
  
  new Card('Scierie', CardType.RAW_MATERIAL, 3, 2),
  new Card('Scierie', CardType.RAW_MATERIAL, 4, 2),
  new Card('Carrière', CardType.RAW_MATERIAL, 3, 2),
  new Card('Carrière', CardType.RAW_MATERIAL, 4, 2),
  new Card('Briquetterie', CardType.RAW_MATERIAL, 3, 2),
  new Card('Briquetterie', CardType.RAW_MATERIAL, 4, 2),
  new Card('Fonderie', CardType.RAW_MATERIAL, 3, 2),
  new Card('Fonderie', CardType.RAW_MATERIAL, 4, 2),

  // Produits Manufacturés
  new Card('Verrerie', CardType.MANUFACTURED_GOOD, 3, 1),
  new Card('Verrerie', CardType.MANUFACTURED_GOOD, 6, 1),
  new Card('Presse', CardType.MANUFACTURED_GOOD, 3, 1),
  new Card('Presse', CardType.MANUFACTURED_GOOD, 6, 1),
  new Card('Métier à Tisser', CardType.MANUFACTURED_GOOD, 3, 1),
  new Card('Métier à Tisser', CardType.MANUFACTURED_GOOD, 6, 1),

  new Card('Verrerie', CardType.MANUFACTURED_GOOD, 3, 2),
  new Card('Verrerie', CardType.MANUFACTURED_GOOD, 5, 2),
  new Card('Presse', CardType.MANUFACTURED_GOOD, 3, 2),
  new Card('Presse', CardType.MANUFACTURED_GOOD, 5, 2),
  new Card('Métier à Tisser', CardType.MANUFACTURED_GOOD, 3, 2),
  new Card('Métier à Tisser', CardType.MANUFACTURED_GOOD, 5, 2),

  // Bâtiments Militaires
  new Card('Palissade', CardType.MILITARY, 3, 1),
  new Card('Palissade', CardType.MILITARY, 7, 1),
  new Card('Caserne', CardType.MILITARY, 3, 1),
  new Card('Caserne', CardType.MILITARY, 5, 1),
  new Card('Tour de garde', CardType.MILITARY, 3, 1),
  new Card('Tour de garde', CardType.MILITARY, 4, 1),

  new Card('Écuries', CardType.MILITARY, 3, 2),
  new Card('Écuries', CardType.MILITARY, 5, 2),
  new Card('Champs de tir', CardType.MILITARY, 3, 2),
  new Card('Champs de tir', CardType.MILITARY, 6, 2),
  new Card('Muraille', CardType.MILITARY, 3, 2),
  new Card('Muraille', CardType.MILITARY, 7, 2),
  new Card("Place d'armes", CardType.MILITARY, 4, 2),
  new Card("Place d'armes", CardType.MILITARY, 6, 2),
  new Card("Place d'armes", CardType.MILITARY, 7, 2),

  new Card("Castrum", CardType.MILITARY, 4, 3),
  new Card("Castrum", CardType.MILITARY, 7, 3),
  new Card('Fortifications', CardType.MILITARY, 3, 3),
  new Card('Fortifications', CardType.MILITARY, 7, 3),
  new Card('Cirque', CardType.MILITARY, 4, 3),
  new Card('Cirque', CardType.MILITARY, 6, 3),
  new Card('Arsenal', CardType.MILITARY, 3, 3),
  new Card('Arsenal', CardType.MILITARY, 5, 3),
  new Card("Atelier de sièges", CardType.MILITARY, 3, 3),
  new Card("Atelier de sièges", CardType.MILITARY, 5, 3),

  // Bâtiments Scientifiques
  new Card('Scriptorium', CardType.SCIENCE, 3, 1),
  new Card('Scriptorium', CardType.SCIENCE, 4, 1),
  new Card('Atelier', CardType.SCIENCE, 3, 1),
  new Card('Atelier', CardType.SCIENCE, 7, 1),
  new Card('Officine', CardType.SCIENCE, 3, 1),
  new Card('Officine', CardType.SCIENCE, 5, 1),

  new Card('Laboratoire', CardType.SCIENCE, 3, 2),
  new Card('Laboratoire', CardType.SCIENCE, 5, 2),
  new Card('Bibliothèque', CardType.SCIENCE, 3, 2),
  new Card('Bibliothèque', CardType.SCIENCE, 6, 2),
  new Card('École', CardType.SCIENCE, 3, 2),
  new Card('École', CardType.SCIENCE, 7, 2),
  new Card('Dispensaire', CardType.SCIENCE, 3, 2),
  new Card('Dispensaire', CardType.SCIENCE, 4, 2),

  new Card('Académie', CardType.SCIENCE, 3, 3),
  new Card('Académie', CardType.SCIENCE, 7, 3),
  new Card('Observatoire', CardType.SCIENCE, 3, 3),
  new Card('Observatoire', CardType.SCIENCE, 7, 3),
  new Card('Université', CardType.SCIENCE, 3, 3),
  new Card('Université', CardType.SCIENCE, 4, 3),
  new Card('Étude', CardType.SCIENCE, 3, 3),
  new Card('Étude', CardType.SCIENCE, 5, 3),
  new Card('Loge', CardType.SCIENCE, 3, 3),
  new Card('Loge', CardType.SCIENCE, 6, 3),

  // Bâtiments Civils
  new Card('Autel', CardType.CIVIL, 3, 1),
  new Card('Autel', CardType.CIVIL, 5, 1),
  new Card('Théâtre', CardType.CIVIL, 3, 1),
  new Card('Théâtre', CardType.CIVIL, 6, 1),
  new Card('Bains', CardType.CIVIL, 3, 1),
  new Card('Bains', CardType.CIVIL, 7, 1),
  new Card('Puits', CardType.CIVIL, 3, 1),
  new Card('Puits', CardType.CIVIL, 7, 1),

  new Card('Aqueduc', CardType.CIVIL, 3, 2),
  new Card('Aqueduc', CardType.CIVIL, 7, 2),
  new Card('Temple', CardType.CIVIL, 3, 2),
  new Card('Temple', CardType.CIVIL, 6, 2),
  new Card('Statue', CardType.CIVIL, 3, 2),
  new Card('Statue', CardType.CIVIL, 7, 2),
  new Card('Tribunal', CardType.CIVIL, 3, 2),
  new Card('Tribunal', CardType.CIVIL, 5, 2),
  
  new Card('Panthéon', CardType.CIVIL, 3, 3),
  new Card('Panthéon', CardType.CIVIL, 6, 3),
  new Card('Jardins', CardType.CIVIL, 3, 3),
  new Card('Jardins', CardType.CIVIL, 4, 3),
  new Card('Hôtel de ville', CardType.CIVIL, 3, 3),
  new Card('Hôtel de ville', CardType.CIVIL, 6, 3),
  new Card('Palace', CardType.CIVIL, 3, 3),
  new Card('Palace', CardType.CIVIL, 7, 3),
  new Card('Sénat', CardType.CIVIL, 3, 3),
  new Card('Sénat', CardType.CIVIL, 5, 3),
  
  // Bâtiments Commerciaux
  new Card('Taverne', CardType.COMMERCIAL, 4, 1),
  new Card('Taverne', CardType.COMMERCIAL, 5, 1),
  new Card('Taverne', CardType.COMMERCIAL, 7, 1),
  new Card('Comptoir Est', CardType.COMMERCIAL, 3, 1),
  new Card('Comptoir Est', CardType.COMMERCIAL, 7, 1),
  new Card('Comptoir Ouest', CardType.COMMERCIAL, 3, 1),
  new Card('Comptoir Ouest', CardType.COMMERCIAL, 7, 1),
  new Card('Marché', CardType.COMMERCIAL, 3, 1),
  new Card('Marché', CardType.COMMERCIAL, 6, 1),

  new Card('Forum', CardType.COMMERCIAL, 3, 2),
  new Card('Forum', CardType.COMMERCIAL, 6, 2),
  new Card('Forum', CardType.COMMERCIAL, 7, 2),
  new Card('Caravansérail', CardType.COMMERCIAL, 3, 2),
  new Card('Caravansérail', CardType.COMMERCIAL, 5, 2),
  new Card('Caravansérail', CardType.COMMERCIAL, 6, 2),
  new Card('Vignoble', CardType.COMMERCIAL, 3, 2),
  new Card('Vignoble', CardType.COMMERCIAL, 6, 2),
  new Card('Bazar', CardType.COMMERCIAL, 4, 2),
  new Card('Bazar', CardType.COMMERCIAL, 7, 2),

  new Card('Port', CardType.COMMERCIAL, 3, 3),
  new Card('Port', CardType.COMMERCIAL, 4, 3),
  new Card('Chambre de commerce', CardType.COMMERCIAL, 4, 3),
  new Card('Chambre de commerce', CardType.COMMERCIAL, 6, 3),
  new Card('Phare', CardType.COMMERCIAL, 3, 3),
  new Card('Phare', CardType.COMMERCIAL, 6, 3),
  new Card('Arène', CardType.COMMERCIAL, 3, 3),
  new Card('Arène', CardType.COMMERCIAL, 5, 3),
  new Card('Ludus', CardType.COMMERCIAL, 5, 3),
  new Card('Ludus', CardType.COMMERCIAL, 7, 3),

  // Guildes
  new Card('Guilde des travailleurs', CardType.GUILD, 3, 3),
  new Card('Guilde des artisans', CardType.GUILD, 3, 3),
  new Card('Guilde des commerçants', CardType.GUILD, 3, 3),
  new Card('Guilde des philosophes', CardType.GUILD, 3, 3),
  new Card('Guilde des espions', CardType.GUILD, 3, 3),
  new Card('Guilde des armateurs', CardType.GUILD, 3, 3),
  new Card('Guilde des scientifiques', CardType.GUILD, 3, 3),
  new Card('Guilde des magistrats', CardType.GUILD, 3, 3),
  new Card('Guilde des bâtisseurs', CardType.GUILD, 3, 3),
  new Card('Guilde des décorateurs', CardType.GUILD, 3, 3),
]; 