export enum CardType {
  CIVIL = 'CIVIL',
  COMMERCIAL = 'COMMERCIAL',
  MILITARY = 'MILITARY',
  SCIENCE = 'SCIENCE',
  GUILD = 'GUILD',
  RAW_MATERIAL = 'RAW_MATERIAL',
  MANUFACTURED_GOOD = 'MANUFACTURED_GOOD'
}
